-- Destiny AI core database schema.
-- Run this in the Supabase SQL Editor.

create table if not exists public.destiny_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  plan text not null default 'free' check (plan in ('free', 'pro')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.destiny_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.destiny_profiles enable row level security;
alter table public.destiny_chat_messages enable row level security;

drop policy if exists "Users can view own profile" on public.destiny_profiles;
drop policy if exists "Users can insert own profile" on public.destiny_profiles;
drop policy if exists "Users can update own profile" on public.destiny_profiles;
create policy "Users can view own profile" on public.destiny_profiles for select using (auth.uid() = user_id);
create policy "Users can insert own profile" on public.destiny_profiles for insert with check (auth.uid() = user_id);
create policy "Users can update own profile" on public.destiny_profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can view own messages" on public.destiny_chat_messages;
drop policy if exists "Users can insert own messages" on public.destiny_chat_messages;
drop policy if exists "Users can delete own messages" on public.destiny_chat_messages;
create policy "Users can view own messages" on public.destiny_chat_messages for select using (auth.uid() = user_id);
create policy "Users can insert own messages" on public.destiny_chat_messages for insert with check (auth.uid() = user_id);
create policy "Users can delete own messages" on public.destiny_chat_messages for delete using (auth.uid() = user_id);

create or replace function public.handle_new_destiny_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.destiny_profiles (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_destiny on auth.users;
create trigger on_auth_user_created_destiny
after insert on auth.users
for each row execute procedure public.handle_new_destiny_user();

create index if not exists destiny_chat_messages_user_created_idx
on public.destiny_chat_messages (user_id, created_at desc);
