create table if not exists public.destiny_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant','system')),
  content text not null,
  mode text not null default 'Chat',
  created_at timestamptz not null default now()
);

create index if not exists destiny_chat_messages_user_created_idx
  on public.destiny_chat_messages(user_id, created_at);

alter table public.destiny_chat_messages enable row level security;

drop policy if exists "Users can read own Destiny AI messages" on public.destiny_chat_messages;
create policy "Users can read own Destiny AI messages"
  on public.destiny_chat_messages for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own Destiny AI messages" on public.destiny_chat_messages;
create policy "Users can insert own Destiny AI messages"
  on public.destiny_chat_messages for insert to authenticated
  with check (auth.uid() = user_id);
